name: CI

on:
  push:
    branches: ['main', 'feat/**']
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CI: 'true'
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check web
        run: npm run typecheck --workspace web

      - name: Build
        run: npm run build

      - name: Unit tests
        run: npm run test

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: E2E tests
        run: npm run e2e

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: artifacts/playwright-report
          if-no-files-found: ignore
